using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <summary>
    /// Couverture de profil, objectifs hebdomadaires et historique des
    /// téléchargements. Écrite en SQL idempotent (même style que les
    /// migrations existantes du projet) : elle peut être rejouée sans
    /// risque sur une base déjà à jour.
    /// </summary>
    public partial class AddCoverWeeklyGoalsDownloadHistory : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // ── 1. Users.CoverUrl ──
            migrationBuilder.Sql(
                @"DO $$
                BEGIN
                    IF NOT EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='Users' AND column_name='CoverUrl')
                    THEN
                        ALTER TABLE ""Users"" ADD COLUMN ""CoverUrl"" character varying(500) NULL;
                    END IF;
                END $$;");

            // ── 2. WeeklyGoals ──
            migrationBuilder.Sql(
                @"CREATE TABLE IF NOT EXISTS ""WeeklyGoals"" (
                    ""Id""               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId""           integer NOT NULL,
                    ""WeekStart""        timestamp with time zone NOT NULL,
                    ""StudyHoursTarget"" integer NULL,
                    ""QuizTarget""       integer NULL,
                    ""DownloadsTarget""  integer NULL,
                    ""CreatedAt""        timestamp with time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt""        timestamp with time zone NULL,
                    CONSTRAINT ""FK_WeeklyGoals_Users_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_WeeklyGoals_UserId_WeekStart""
                    ON ""WeeklyGoals"" (""UserId"", ""WeekStart"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_WeeklyGoals_UserId""
                    ON ""WeeklyGoals"" (""UserId"");");

            // ── 3. DownloadHistories ──
            migrationBuilder.Sql(
                @"CREATE TABLE IF NOT EXISTS ""DownloadHistories"" (
                    ""Id""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId""    integer NOT NULL,
                    ""SubjectId"" integer NOT NULL,
                    ""ExamId""    integer NULL,
                    ""FileName""  character varying(300) NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""FK_DownloadHistories_Users_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_DownloadHistories_Subjects_SubjectId""
                        FOREIGN KEY (""SubjectId"") REFERENCES ""Subjects"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_DownloadHistories_UserId_CreatedAt""
                    ON ""DownloadHistories"" (""UserId"", ""CreatedAt"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_DownloadHistories_SubjectId""
                    ON ""DownloadHistories"" (""SubjectId"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""DownloadHistories"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""WeeklyGoals"";");

            migrationBuilder.Sql(
                @"DO $$
                BEGIN
                    IF EXISTS(SELECT 1 FROM information_schema.columns WHERE table_name='Users' AND column_name='CoverUrl')
                    THEN
                        ALTER TABLE ""Users"" DROP COLUMN ""CoverUrl"";
                    END IF;
                END $$;");
        }
    }
}
