using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <summary>
    /// Module 33 (lot 7) : table de paramétrage du déclenchement hybride de
    /// l'album de fin d'année (AlbumSchedule) + indicateur d'aperçu en
    /// attente sur ParentReports. SQL idempotent, dans le style des
    /// migrations existantes du projet.
    /// </summary>
    public partial class AddAlbumSchedule : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"ALTER TABLE ""ParentReports""
                    ADD COLUMN IF NOT EXISTS ""IsPreviewPending"" boolean NOT NULL DEFAULT false;");

            migrationBuilder.Sql(
                @"CREATE TABLE IF NOT EXISTS ""AlbumSchedules"" (
                    ""Id""                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""SchoolYear""          varchar(20) NOT NULL,
                    ""TriggerDate""         timestamp with time zone NOT NULL,
                    ""Status""              varchar(20) NOT NULL DEFAULT 'Pending',
                    ""GeneratedAt""         timestamp with time zone NULL,
                    ""DispatchedAt""        timestamp with time zone NULL,
                    ""CreatedByUserId""     integer NOT NULL,
                    ""DispatchedByUserId""  integer NULL,
                    ""CreatedAt""           timestamp with time zone NOT NULL DEFAULT now(),
                    ""UpdatedAt""           timestamp with time zone NULL,
                    CONSTRAINT ""FK_AlbumSchedules_Users_CreatedByUserId""
                        FOREIGN KEY (""CreatedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT,
                    CONSTRAINT ""FK_AlbumSchedules_Users_DispatchedByUserId""
                        FOREIGN KEY (""DispatchedByUserId"") REFERENCES ""Users"" (""Id"") ON DELETE RESTRICT
                );");

            migrationBuilder.Sql(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AlbumSchedules_SchoolYear""
                    ON ""AlbumSchedules"" (""SchoolYear"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_ParentReports_ReportType_IsPreviewPending""
                    ON ""ParentReports"" (""ReportType"", ""IsPreviewPending"");");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_ParentReports_ReportType_IsPreviewPending"";");
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""AlbumSchedules"";");
            migrationBuilder.Sql(@"ALTER TABLE ""ParentReports"" DROP COLUMN IF EXISTS ""IsPreviewPending"";");
        }
    }
}
