using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace Backend.Migrations;

/// <summary>
/// Partie 8 du suivi — quota WinAI facturé au token réel.
///
/// Contenu identique au script jumeau <c>Migrations/SQL_SeedPricingPlanTokenQuotas.sql</c>,
/// qui est le chemin d'application réel : comme toutes les migrations manuelles
/// de ce projet, cette classe ne porte pas d'attribut <c>[Migration]</c> et
/// n'est donc pas embarquée par <c>dotnet ef database update</c>.
///
/// ⚠ <b>Ordre de déploiement obligatoire</b> : le script SQL AVANT le code qui
/// lit <c>AiTokenUsages</c>. Sans lui, <c>GET /api/subscriptions/me</c> reste
/// fonctionnel (état par défaut) mais WinAI refuse chaque message en 503.
///
/// Rejouable (IF NOT EXISTS, mises à jour conditionnelles).
///
/// 1. Crée la table <c>AiTokenUsages</c> (journal par message, idempotence 8.7).
/// 2. (8.10) Ajoute la colonne <c>AttemptId</c> (tentative détentrice d'une
///    réserve ouverte : seule elle peut la libérer).
/// 3. (8.10) Ajoute l'index couvrant de la lecture par fenêtre glissante
///    (UserId, CreatedAt) INCLUDE (TokensCharged).
/// 4. Écrit dans <c>PricingPlans."MaxChatMessages"</c> le quota de RÉFÉRENCE
///    en tokens (8.10 : plus un plafond mensuel ; semaine = référence ÷ 4,
///    session = semaine ÷ 3, voir <c>Services/AiUsagePolicy.cs</c>).
/// </summary>
public partial class AiTokenQuotas : Migration
{
    /// <inheritdoc />
    protected override void Up(MigrationBuilder migrationBuilder)
    {
        migrationBuilder.Sql(@"
CREATE TABLE IF NOT EXISTS ""AiTokenUsages"" (
    ""Id""              integer GENERATED BY DEFAULT AS IDENTITY,
    ""UserId""          integer NOT NULL,
    ""ClientMessageId"" character varying(64) NOT NULL,
    ""TokensCharged""   integer NOT NULL DEFAULT 0,
    ""IsFinalized""     boolean NOT NULL DEFAULT FALSE,
    ""Source""          character varying(20) NOT NULL DEFAULT 'stream',
    ""CreatedAt""       timestamp with time zone NOT NULL,
    ""FinalizedAt""     timestamp with time zone,
    CONSTRAINT ""PK_AiTokenUsages"" PRIMARY KEY (""Id""),
    CONSTRAINT ""FK_AiTokenUsages_Users_UserId"" FOREIGN KEY (""UserId"")
        REFERENCES ""Users"" (""Id"") ON DELETE CASCADE
);
CREATE UNIQUE INDEX IF NOT EXISTS ""IX_AiTokenUsages_UserId_ClientMessageId""
    ON ""AiTokenUsages"" (""UserId"", ""ClientMessageId"");
ALTER TABLE ""AiTokenUsages"" ADD COLUMN IF NOT EXISTS ""AttemptId"" character varying(32);
CREATE INDEX IF NOT EXISTS ""IX_AiTokenUsages_UserId_CreatedAt""
    ON ""AiTokenUsages"" (""UserId"", ""CreatedAt"");
CREATE INDEX IF NOT EXISTS ""IX_AiTokenUsages_UserId_CreatedAt_Window""
    ON ""AiTokenUsages"" (""UserId"", ""CreatedAt"") INCLUDE (""TokensCharged"");");

        migrationBuilder.Sql(
            @"UPDATE ""PricingPlans"" SET ""MaxChatMessages"" = v.""quota""
              FROM (VALUES
                  ('Starter',  'students',  200000),
                  ('Standard', 'students',  800000),
                  ('Premium',  'students', 2000000),
                  ('Annuel',   'students', 3000000),
                  ('Basique',  'teachers',  200000),
                  ('Pro',      'teachers', 2400000),
                  ('Expert',   'teachers', 5000000),
                  ('Famille',  'parents',  1000000),
                  ('Famille+', 'parents',  2000000),
                  ('VIP',      'parents',  4000000)
              ) AS v(""name"", ""category"", ""quota"")
              WHERE ""PricingPlans"".""Name"" = v.""name""
                AND ""PricingPlans"".""Category"" = v.""category""
                AND (""PricingPlans"".""MaxChatMessages"" IS NULL OR ""PricingPlans"".""MaxChatMessages"" < 100000);");

        migrationBuilder.Sql(
            @"UPDATE ""PricingPlans"" SET ""MaxChatMessages"" = 800000
              WHERE (""MaxChatMessages"" IS NULL OR ""MaxChatMessages"" < 100000) AND ""Price"" > 0;");

        migrationBuilder.Sql(
            @"UPDATE ""PricingPlans"" SET ""MaxChatMessages"" = 200000
              WHERE (""MaxChatMessages"" IS NULL OR ""MaxChatMessages"" < 100000) AND ""Price"" <= 0;");
    }

    /// <inheritdoc />
    protected override void Down(MigrationBuilder migrationBuilder)
    {
        // Retour à la colonne non renseignée : AiQuotaService retombe sur son
        // repli (même grille). La table de journal est supprimée.
        migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""AiTokenUsages"";");
        migrationBuilder.Sql(@"UPDATE ""PricingPlans"" SET ""MaxChatMessages"" = NULL;");
    }
}
