using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace backend.Migrations
{
    /// <summary>
    /// Forum : table des fils suivis + index de tri.
    /// SQL idempotent, dans le style des migrations existantes du projet.
    /// </summary>
    public partial class AddForumThreadFollows : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(
                @"CREATE TABLE IF NOT EXISTS ""ForumThreadFollows"" (
                    ""Id""        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""UserId""    integer NOT NULL,
                    ""ThreadId""  integer NOT NULL,
                    ""CreatedAt"" timestamp with time zone NOT NULL DEFAULT now(),
                    CONSTRAINT ""FK_ForumThreadFollows_Users_UserId""
                        FOREIGN KEY (""UserId"") REFERENCES ""Users"" (""Id"") ON DELETE CASCADE,
                    CONSTRAINT ""FK_ForumThreadFollows_ForumThreads_ThreadId""
                        FOREIGN KEY (""ThreadId"") REFERENCES ""ForumThreads"" (""Id"") ON DELETE CASCADE
                );");

            migrationBuilder.Sql(
                @"CREATE UNIQUE INDEX IF NOT EXISTS ""IX_ForumThreadFollows_UserId_ThreadId""
                    ON ""ForumThreadFollows"" (""UserId"", ""ThreadId"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_ForumThreadFollows_ThreadId""
                    ON ""ForumThreadFollows"" (""ThreadId"");");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_ForumThreads_Category_CreatedAt""
                    ON ""ForumThreads"" (""Category"", ""CreatedAt"" DESC);");

            migrationBuilder.Sql(
                @"CREATE INDEX IF NOT EXISTS ""IX_ForumThreads_RepliesCount""
                    ON ""ForumThreads"" (""RepliesCount"" DESC);");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql(@"DROP TABLE IF EXISTS ""ForumThreadFollows"";");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_ForumThreads_Category_CreatedAt"";");
            migrationBuilder.Sql(@"DROP INDEX IF EXISTS ""IX_ForumThreads_RepliesCount"";");
        }
    }
}
