-- PostgreSQL Migration Script for Win+ User Settings Tables
-- This script will be generated by EF Core migrations
-- Run AFTER validation script confirms tables don't exist

-- Create UserNotificationSettings table
CREATE TABLE IF NOT EXISTS "UserNotificationSettings" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "EmailNotifications" BOOLEAN NOT NULL DEFAULT true,
    "PushNotifications" BOOLEAN NOT NULL DEFAULT true,
    "CourseCommunity" BOOLEAN NOT NULL DEFAULT true,
    "Promotions" BOOLEAN NOT NULL DEFAULT false,
    "Newsletters" BOOLEAN NOT NULL DEFAULT true,
    "LearningReminders" BOOLEAN NOT NULL DEFAULT true,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_UserNotificationSettings_Users_UserId" 
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_UserNotificationSettings_UserId" 
        UNIQUE ("UserId")
);

-- Create UserPrivacySettings table
CREATE TABLE IF NOT EXISTS "UserPrivacySettings" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "ProfileVisible" BOOLEAN NOT NULL DEFAULT true,
    "ShowProgressPublic" BOOLEAN NOT NULL DEFAULT false,
    "AllowMessages" BOOLEAN NOT NULL DEFAULT true,
    "AllowFriends" BOOLEAN NOT NULL DEFAULT true,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_UserPrivacySettings_Users_UserId" 
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_UserPrivacySettings_UserId" 
        UNIQUE ("UserId")
);

-- Create UserTwoFactorAuthentication table
CREATE TABLE IF NOT EXISTS "UserTwoFactorAuthentication" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "IsEnabled" BOOLEAN NOT NULL DEFAULT false,
    "Method" VARCHAR(50),
    "TotpSecret" VARCHAR(255),
    "BackupCodes" TEXT,
    "BackupCodesUsed" INTEGER NOT NULL DEFAULT 0,
    "EnabledAt" TIMESTAMP,
    "LastVerifiedAt" TIMESTAMP,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "UpdatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "FK_UserTwoFactorAuthentication_Users_UserId" 
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE,
    CONSTRAINT "UQ_UserTwoFactorAuthentication_UserId" 
        UNIQUE ("UserId")
);

-- Create UserSessions table
CREATE TABLE IF NOT EXISTS "UserSessions" (
    "Id" SERIAL PRIMARY KEY,
    "UserId" INTEGER NOT NULL,
    "DeviceName" VARCHAR(255),
    "DeviceType" VARCHAR(100),
    "IpAddress" VARCHAR(45),
    "UserAgent" TEXT,
    "Location" VARCHAR(255),
    "RefreshTokenId" INTEGER,
    "CreatedAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "LastActivityAt" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "ExpiresAt" TIMESTAMP NOT NULL,
    "IsActive" BOOLEAN NOT NULL DEFAULT true,
    CONSTRAINT "FK_UserSessions_Users_UserId" 
        FOREIGN KEY ("UserId") REFERENCES "Users"("Id") ON DELETE CASCADE
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS "IX_UserNotificationSettings_UserId" 
    ON "UserNotificationSettings" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_UserPrivacySettings_UserId" 
    ON "UserPrivacySettings" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_UserTwoFactorAuthentication_UserId" 
    ON "UserTwoFactorAuthentication" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_UserSessions_UserId" 
    ON "UserSessions" ("UserId");

CREATE INDEX IF NOT EXISTS "IX_UserSessions_IsActive" 
    ON "UserSessions" ("IsActive");

CREATE INDEX IF NOT EXISTS "IX_UserSessions_ExpiresAt" 
    ON "UserSessions" ("ExpiresAt");

-- Add update trigger for UpdatedAt timestamp (optional but recommended)
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW."UpdatedAt" = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Create triggers for each settings table
DROP TRIGGER IF EXISTS update_UserNotificationSettings_updated_at ON "UserNotificationSettings";
CREATE TRIGGER update_UserNotificationSettings_updated_at 
    BEFORE UPDATE ON "UserNotificationSettings"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_UserPrivacySettings_updated_at ON "UserPrivacySettings";
CREATE TRIGGER update_UserPrivacySettings_updated_at 
    BEFORE UPDATE ON "UserPrivacySettings"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

DROP TRIGGER IF EXISTS update_UserTwoFactorAuthentication_updated_at ON "UserTwoFactorAuthentication";
CREATE TRIGGER update_UserTwoFactorAuthentication_updated_at 
    BEFORE UPDATE ON "UserTwoFactorAuthentication"
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- Verify tables were created
SELECT EXISTS (
    SELECT 1 FROM information_schema.TABLES 
    WHERE TABLE_SCHEMA = 'public' AND TABLE_NAME = 'UserNotificationSettings'
) as UserNotificationSettings_Created,
EXISTS (
    SELECT 1 FROM information_schema.TABLES 
    WHERE TABLE_SCHEMA = 'public' AND TABLE_NAME = 'UserPrivacySettings'
) as UserPrivacySettings_Created,
EXISTS (
    SELECT 1 FROM information_schema.TABLES 
    WHERE TABLE_SCHEMA = 'public' AND TABLE_NAME = 'UserTwoFactorAuthentication'
) as UserTwoFactorAuthentication_Created,
EXISTS (
    SELECT 1 FROM information_schema.TABLES 
    WHERE TABLE_SCHEMA = 'public' AND TABLE_NAME = 'UserSessions'
) as UserSessions_Created;
