-- ═══════════════════════════════════════════════════════════════════
-- Module 33 (lot 7)  déclenchement hybride de l'album de fin d'année
--
-- Ajoute :
--   - ParentReports.IsPreviewPending (aperçu généré automatiquement, pas
--     encore diffusé  masqué à l'écran parent tant que vrai)
--   - AlbumSchedules (paramètre administrateur : date de fin d'année
--     scolaire configurable, jamais codée en dur ni en fichier de config)
--
-- Idempotent : rejouable sans risque.
--
-- Depuis l'EC2 :
--   psql "host=<endpoint>.rds.amazonaws.com port=5432 dbname=winplus \
--         user=<user> sslmode=require" -f SQL_AddAlbumSchedule.sql
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

ALTER TABLE "ParentReports"
    ADD COLUMN IF NOT EXISTS "IsPreviewPending" boolean NOT NULL DEFAULT false;

CREATE TABLE IF NOT EXISTS "AlbumSchedules" (
    "Id"                  integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "SchoolYear"          varchar(20) NOT NULL,
    "TriggerDate"         timestamp with time zone NOT NULL,
    "Status"              varchar(20) NOT NULL DEFAULT 'Pending',
    "GeneratedAt"         timestamp with time zone NULL,
    "DispatchedAt"        timestamp with time zone NULL,
    "CreatedByUserId"     integer NOT NULL,
    "DispatchedByUserId"  integer NULL,
    "CreatedAt"           timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt"           timestamp with time zone NULL,
    CONSTRAINT "FK_AlbumSchedules_Users_CreatedByUserId"
        FOREIGN KEY ("CreatedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_AlbumSchedules_Users_DispatchedByUserId"
        FOREIGN KEY ("DispatchedByUserId") REFERENCES "Users" ("Id") ON DELETE RESTRICT
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AlbumSchedules_SchoolYear"
    ON "AlbumSchedules" ("SchoolYear");

CREATE INDEX IF NOT EXISTS "IX_ParentReports_ReportType_IsPreviewPending"
    ON "ParentReports" ("ReportType", "IsPreviewPending");

-- Marquer la migration comme passée (sinon EF la rejouera)
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20261008_AddAlbumSchedule',
       COALESCE((SELECT "ProductVersion" FROM "__EFMigrationsHistory" LIMIT 1), '8.0.0')
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20261008_AddAlbumSchedule'
);

COMMIT;

-- Vérification
SELECT table_name FROM information_schema.tables WHERE table_name = 'AlbumSchedules';
SELECT column_name FROM information_schema.columns
WHERE table_name = 'ParentReports' AND column_name = 'IsPreviewPending';

-- Retour arrière
-- ALTER TABLE "ParentReports" DROP COLUMN IF EXISTS "IsPreviewPending";
-- DROP TABLE IF EXISTS "AlbumSchedules";
