-- ═══════════════════════════════════════════════════════════════════
-- Forum — fils suivis
--
-- Une table, deux index. Idempotent : rejouable sans risque.
--
-- Depuis l'EC2 :
--   psql "host=<endpoint>.rds.amazonaws.com port=5432 dbname=winplus \
--         user=<user> sslmode=require" -f SQL_AddForumThreadFollows.sql
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE IF NOT EXISTS "ForumThreadFollows" (
    "Id"        integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"    integer NOT NULL,
    "ThreadId"  integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT "FK_ForumThreadFollows_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_ForumThreadFollows_ForumThreads_ThreadId"
        FOREIGN KEY ("ThreadId") REFERENCES "ForumThreads" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ForumThreadFollows_UserId_ThreadId"
    ON "ForumThreadFollows" ("UserId", "ThreadId");

CREATE INDEX IF NOT EXISTS "IX_ForumThreadFollows_ThreadId"
    ON "ForumThreadFollows" ("ThreadId");

-- Index de tri sur les fils (accélère sort=active / unanswered / popular)
CREATE INDEX IF NOT EXISTS "IX_ForumThreads_Category_CreatedAt"
    ON "ForumThreads" ("Category", "CreatedAt" DESC);

CREATE INDEX IF NOT EXISTS "IX_ForumThreads_RepliesCount"
    ON "ForumThreads" ("RepliesCount" DESC);

-- Marquer la migration comme passée (sinon EF la rejouera)
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260828_AddForumThreadFollows',
       COALESCE((SELECT "ProductVersion" FROM "__EFMigrationsHistory" LIMIT 1), '8.0.0')
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory"
    WHERE "MigrationId" = '20260828_AddForumThreadFollows'
);

COMMIT;

-- Vérification
SELECT table_name FROM information_schema.tables
WHERE table_name = 'ForumThreadFollows';

-- Retour arrière
-- DROP TABLE IF EXISTS "ForumThreadFollows";
