-- ════════════════════════════════════════════════════════════════════════════
-- SQL_SeedPricingPlanTokenQuotas.sql   Partie 8 du suivi (quota IA au token réel)
--                                         révisé en 8.10 (limites session / semaine)
--
-- ⚠⚠ ORDRE DE DÉPLOIEMENT OBLIGATOIRE ⚠⚠
--
--   1. Exécuter CE script sur la base.
--   2. SEULEMENT ENSUITE, déployer le code .NET et Python qui lit
--      "AiTokenUsages" (Services/AiQuotaService.cs, python/services/ai_quota.py).
--
--   Code déployé avant le script : GET /api/subscriptions/me reste
--   fonctionnel (état par défaut, avertissement journalisé), mais WinAI refuse
--   proprement chaque message (503 « quota_unavailable ») tant que la table ou
--   la colonne "AttemptId" manquent.
--
--   psql -U <user> -d winplus -f Migrations/SQL_SeedPricingPlanTokenQuotas.sql
--
-- Jumeau de Migrations/20260924150000_AiTokenQuotas.cs (même contenu). Comme
-- les autres migrations manuelles du projet, la classe C# ne porte pas
-- d'attribut [Migration] : le chemin d'application réel est CE script.
--
-- REJOUABLE : chaque instruction est idempotente (IF NOT EXISTS, mises à jour
-- conditionnelles). Le rejouer sur une base déjà migrée ne change rien.
--
-- 1. Crée "AiTokenUsages", journal de consommation en tokens LLM réels, avec
--    l'index unique (UserId, ClientMessageId) qui porte l'idempotence par
--    message (décision 8.7).
--
-- 2. (8.10) Ajoute "AttemptId" : tentative qui détient une réserve ouverte.
--    Une libération n'est appliquée que par la tentative détentrice (le flux
--    SSE abandonné ne peut plus supprimer la réserve rattachée par le repli
--    REST du même message).
--
-- 3. (8.10) Index couvrant pour la lecture par fenêtre glissante : la requête
--      SELECT "CreatedAt", "TokensCharged" FROM "AiTokenUsages"
--      WHERE "UserId" = $1 AND "CreatedAt" > now() - 7 jours
--    est servie par un parcours d'index seul (Postgres ≥ 11 ; la base est en
--    14). L'index (UserId, CreatedAt) d'origine est conservé : la version
--    déployée précédente du code s'appuie sur lui.
--
-- 4. "PricingPlans"."MaxChatMessages" porte le quota de RÉFÉRENCE du plan en
--    tokens. Depuis 8.10 ce n'est PLUS un plafond mensuel appliqué : le code
--    en dérive la limite hebdomadaire (référence ÷ 4) et la limite de session
--    (un tiers de la semaine), voir Services/AiUsagePolicy.cs. Les valeurs à
--    l'échelle « messages » (< 100 000) sont remplacées ; une valeur déjà à
--    l'échelle « tokens » (>= 100 000), réglée par un administrateur, n'est
--    jamais écrasée.
--
--   Plan       Catégorie   Prix           Référence   Semaine    Session   Mult.
--   Starter    students          0 F/mois    200 000     50 000    16 666    1x
--   Standard   students      5 900 F/mois    800 000    200 000    66 666    4x
--   Premium    students     11 900 F/mois  2 000 000    500 000   166 666   10x
--   Annuel     students     89 900 F/an    3 000 000    750 000   250 000   15x
--   Basique    teachers          0 F/mois    200 000     50 000    16 666    1x
--   Pro        teachers     17 900 F/mois  2 400 000    600 000   200 000   12x
--   Expert     teachers     35 900 F/mois  5 000 000  1 250 000   416 666   25x
--   Famille    parents       8 900 F/mois  1 000 000    250 000    83 333    5x
--   Famille+   parents      14 900 F/mois  2 000 000    500 000   166 666   10x
--   VIP        parents      26 900 F/mois  4 000 000  1 000 000   333 333   20x
--
-- Plan gratuit : 50 000 tokens/semaine ≈ 35 échanges réels à ~1 400 tokens,
-- soit ~5 par jour, cohérent avec la promesse « 5 messages/jour en gratuit ».
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE IF NOT EXISTS "AiTokenUsages" (
    "Id"              integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"          integer NOT NULL,
    "ClientMessageId" character varying(64) NOT NULL,
    "TokensCharged"   integer NOT NULL DEFAULT 0,
    "IsFinalized"     boolean NOT NULL DEFAULT FALSE,
    "Source"          character varying(20) NOT NULL DEFAULT 'stream',
    "CreatedAt"       timestamp with time zone NOT NULL,
    "FinalizedAt"     timestamp with time zone,
    CONSTRAINT "PK_AiTokenUsages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_AiTokenUsages_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

-- 8.10 : tentative détentrice de la réserve (voir en-tête, point 2).
ALTER TABLE "AiTokenUsages" ADD COLUMN IF NOT EXISTS "AttemptId" character varying(32);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_AiTokenUsages_UserId_ClientMessageId"
    ON "AiTokenUsages" ("UserId", "ClientMessageId");

CREATE INDEX IF NOT EXISTS "IX_AiTokenUsages_UserId_CreatedAt"
    ON "AiTokenUsages" ("UserId", "CreatedAt");

-- 8.10 : index couvrant de la lecture par fenêtre (voir en-tête, point 3).
CREATE INDEX IF NOT EXISTS "IX_AiTokenUsages_UserId_CreatedAt_Window"
    ON "AiTokenUsages" ("UserId", "CreatedAt") INCLUDE ("TokensCharged");

UPDATE "PricingPlans" SET "MaxChatMessages" = v."quota"
FROM (VALUES
    ('Starter',  'students',   200000),
    ('Standard', 'students',   800000),
    ('Premium',  'students',  2000000),
    ('Annuel',   'students',  3000000),
    ('Basique',  'teachers',   200000),
    ('Pro',      'teachers',  2400000),
    ('Expert',   'teachers',  5000000),
    ('Famille',  'parents',   1000000),
    ('Famille+', 'parents',   2000000),
    ('VIP',      'parents',   4000000)
) AS v("name", "category", "quota")
WHERE "PricingPlans"."Name" = v."name"
  AND "PricingPlans"."Category" = v."category"
  AND ("PricingPlans"."MaxChatMessages" IS NULL OR "PricingPlans"."MaxChatMessages" < 100000);

-- Filet de sécurité : tout autre plan encore à l'échelle « messages ».
UPDATE "PricingPlans" SET "MaxChatMessages" = 800000
WHERE ("MaxChatMessages" IS NULL OR "MaxChatMessages" < 100000) AND "Price" > 0;

UPDATE "PricingPlans" SET "MaxChatMessages" = 200000
WHERE ("MaxChatMessages" IS NULL OR "MaxChatMessages" < 100000) AND "Price" <= 0;

COMMIT;
