-- ═══════════════════════════════════════════════════════════════════
-- WinPlus — couverture de profil + objectif hebdomadaire
-- PostgreSQL. Noms de colonnes en PascalCase entre guillemets, comme
-- le reste du schéma EF Core du projet.
--
-- Préférer la migration EF (voir README-PATCH.md) ; ce script est
-- l'équivalent SQL pour un environnement où EF n'est pas lancé.
-- ═══════════════════════════════════════════════════════════════════

BEGIN;

-- ── 1. Image de couverture sur l'utilisateur ──────────────────────

ALTER TABLE "Users"
    ADD COLUMN IF NOT EXISTS "CoverUrl" character varying(500) NULL;

-- ── 2. Objectifs hebdomadaires ────────────────────────────────────

CREATE TABLE IF NOT EXISTS "WeeklyGoals" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "UserId"           integer NOT NULL,
    "WeekStart"        timestamp with time zone NOT NULL,
    "StudyHoursTarget" integer NULL,
    "QuizTarget"       integer NULL,
    "DownloadsTarget"  integer NULL,
    "CreatedAt"        timestamp with time zone NOT NULL DEFAULT now(),
    "UpdatedAt"        timestamp with time zone NULL,
    CONSTRAINT "FK_WeeklyGoals_Users_UserId"
        FOREIGN KEY ("UserId") REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "IX_WeeklyGoals_UserId_WeekStart"
    ON "WeeklyGoals" ("UserId", "WeekStart");

CREATE INDEX IF NOT EXISTS "IX_WeeklyGoals_UserId"
    ON "WeeklyGoals" ("UserId");

COMMIT;

-- ── Retour arrière ────────────────────────────────────────────────
-- BEGIN;
-- DROP TABLE IF EXISTS "WeeklyGoals";
-- ALTER TABLE "Users" DROP COLUMN IF EXISTS "CoverUrl";
-- COMMIT;
