-- ════════════════════════════════════════════════════════════════════════════
-- SQL_AddChatbotTables.sql
--
-- Crée les tables Conversations / Messages / ChatbotContexts.
--
-- Pourquoi ce script existe : ces tables sont censées être créées par la
-- migration Migrations/20260202_AddChatbotTables.cs, mais cette migration
-- n'avait pas d'attribut [Migration]. EF Core ne reconnaît une classe comme
-- migration que si cet attribut est présent : la migration n'apparaissait donc
-- pas dans `dotnet ef migrations list` et n'a jamais été appliquée. Les tables
-- n'existent pas dans la base déployée, et GET /api/admin/winai/stats échoue
-- avec 42P01 (relation inexistante) → 500.
--
-- Le script est idempotent : il peut être rejoué sans risque. Il enregistre
-- aussi la migration dans __EFMigrationsHistory pour qu'un futur
-- `dotnet ef database update` ne tente pas de recréer les tables.
--
-- Exécution :
--   psql "$CONNECTION_STRING" -f SQL_AddChatbotTables.sql
-- ════════════════════════════════════════════════════════════════════════════

BEGIN;

CREATE TABLE IF NOT EXISTS "Conversations" (
    "Id"            integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"        integer NOT NULL,
    "Title"         character varying(255) NOT NULL,
    "Tags"          jsonb,
    "Metadata"      jsonb,
    "IsActive"      boolean NOT NULL DEFAULT TRUE,
    "LastMessageAt" timestamp with time zone,
    "MessageCount"  integer NOT NULL DEFAULT 0,
    "CreatedAt"     timestamp with time zone NOT NULL,
    "UpdatedAt"     timestamp with time zone NOT NULL,
    "IsDeleted"     boolean NOT NULL DEFAULT FALSE,
    "DeletedAt"     timestamp with time zone,
    CONSTRAINT "PK_Conversations" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Conversations_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "Messages" (
    "Id"               integer GENERATED BY DEFAULT AS IDENTITY,
    "ConversationId"   integer NOT NULL,
    "Role"             character varying(20) NOT NULL,
    "Content"          text NOT NULL,
    "Attachments"      jsonb,
    "TokensUsed"       integer,
    "FeedbackRating"   integer,
    "FeedbackComment"  character varying(1000),
    "GenerationTimeMs" integer,
    "CreatedAt"        timestamp with time zone NOT NULL,
    "IsDeleted"        boolean NOT NULL DEFAULT FALSE,
    CONSTRAINT "PK_Messages" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Messages_Conversations_ConversationId" FOREIGN KEY ("ConversationId")
        REFERENCES "Conversations" ("Id") ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS "ChatbotContexts" (
    "Id"                integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId"            integer NOT NULL,
    "EducationLevel"    character varying(50),
    "Grade"             character varying(50),
    "UserObjectives"    jsonb,
    "EnrolledSubjects"  jsonb,
    "RecentActivity"    jsonb,
    "NavigationHistory" jsonb,
    "Preferences"       jsonb,
    "Strengths"         jsonb,
    "Weaknesses"        jsonb,
    "LearningStyle"     character varying(50),
    "CreatedAt"         timestamp with time zone NOT NULL,
    "UpdatedAt"         timestamp with time zone NOT NULL,
    CONSTRAINT "PK_ChatbotContexts" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_ChatbotContexts_Users_UserId" FOREIGN KEY ("UserId")
        REFERENCES "Users" ("Id") ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS "IX_Conversations_UserId"        ON "Conversations" ("UserId");
CREATE INDEX IF NOT EXISTS "IX_Conversations_IsActive"      ON "Conversations" ("IsActive");
CREATE INDEX IF NOT EXISTS "IX_Conversations_LastMessageAt" ON "Conversations" ("LastMessageAt");
CREATE INDEX IF NOT EXISTS "IX_Conversations_IsDeleted"     ON "Conversations" ("IsDeleted");

CREATE INDEX IF NOT EXISTS "IX_Messages_ConversationId" ON "Messages" ("ConversationId");
CREATE INDEX IF NOT EXISTS "IX_Messages_CreatedAt"      ON "Messages" ("CreatedAt");
CREATE INDEX IF NOT EXISTS "IX_Messages_IsDeleted"      ON "Messages" ("IsDeleted");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_ChatbotContexts_UserId" ON "ChatbotContexts" ("UserId");

-- Marque la migration comme appliquée pour qu'EF ne la rejoue pas.
INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
SELECT '20260202_AddChatbotTables', '8.0.0'
WHERE NOT EXISTS (
    SELECT 1 FROM "__EFMigrationsHistory" WHERE "MigrationId" = '20260202_AddChatbotTables'
);

COMMIT;

-- Vérification
SELECT table_name
FROM information_schema.tables
WHERE table_schema = 'public'
  AND table_name IN ('Conversations', 'Messages', 'ChatbotContexts')
ORDER BY table_name;
